### ISSUE TITLE
Error with `drom new`

### ISSUE THREAD

**Issue by francoisthire** [OCamlPro/drom#69] opened 2020-11-27 12:53 UTC
Using `drom new <my-project>` I get the following error message:

```bash
saroupille@saroupille:/tmp$ drom new my-project
Creating project "my-project" with skeleton "program", license "LGPL2"
  and sources in src/my-project:
Creating directory my-project
Error: Could not parse: toml template at Error in <string> at line 5 at column 17 (position 61): Forbidden escaped char
```

Here is the version I use:

```bash
saroupille@saroupille:~/Git$ opam switch
#  switch                                     compiler                    description
→  default                                    ocaml-system.4.11.1         default
saroupille@saroupille:~/Git$ opam list drom
# Packages matching: (installed | available) & name-match(drom)
# Package  # Installed # Synopsis
drom.0.2.0 0.2.0       The drom tool is a wrapper over opam/dune in an attempt to provide a cargo-like user experience
```#

**Comment by lefessan** [comment] 2020-11-27 13:59
This is probably a duplicate of #63. Does your name contains an utf8 character ? like the ç of françois ? (for example in your email in ~/.gitconfig). You can check by using `drom new project -v` and check the "authors" field that `drom` created.
As a temporary solution, you might use: DROM_USER="My Name <myname@email.com>" drom new project

**Comment by lefessan** [comment] 2020-11-27 13:59
If yes, the bug is fixed in the current `master`

**Comment by francoisthire** [comment] 2020-11-27 14:23
Indeed, my `.gitconfig` contains utf8 characters. However, I tried to use the `master` version and it still fails. Removing utf8 characters in my `gitconfig` makes `drom new project` to succeed though.

What I observe on the output of `drom new project -v` on master is given below:
```bash
Creating project "project" with skeleton "program", license "LGPL2"
  and sources in src/project:
Creating directory project
Loading project from:
<<<<
[project]
drom-version = "0.1.0"

[project]
authors = ["François Thiré <...>"]

[...]

>>>>>
Loading project from:
<<<<
[project]
drom-version = "0.1.0"

[project]
authors = ["Fran\195\167ois Thir\195\169 <...>"]
copyright = "François Thiré <...>"

[...]
```

**Comment by lefessan** [comment] 2020-11-27 14:26
Did you do `opam install .` to install `drom` from the `master` branch ?
Skeletons are files installed in `$OPAM_SWITCH_PREFIX/share/drom` and you need to update them to fix the bug.

**Comment by lefessan** [comment] 2020-11-27 14:28
Indeed, I will try to understand why the fix didn't work.

**Comment by lefessan** [comment] 2020-11-27 14:35
Should be fixed in #70

**Comment by francoisthire** [comment] 2020-11-27 14:48
I confirm that #70 fixes my issue, thanks :ok_hand:

**Comment by lefessan** [comment] 2020-11-27 15:04
Thanks !

**Closed by lefessan** 2020-11-27 15:04 UTC
